kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:16-alpine
    commands:
      - npm install
      - npm run build
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
    when:
      event: tag
